version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    container_name: longboard
    image: 'edxops/longboard:latest'
    volumes:
      - '.:/edx/app:delegated'
      - 'notused:/edx/app/node_modules'
    ports:
      - '1991:1991'
    environment:
      - NODE_ENV=development
volumes:
  notused: null
